### ISSUE TITLE
リモートにブランチがプッシュできません。

### ISSUE THREAD

**Issue by nobuoooo** [SonicGarden/sg-romanizer#14]
夜分に失礼致します。

リモートにブランチをプッシュしようとしたところ、下記のエラーでプッシュすることができません。
課題のリポジトリからフォークしてmainブランチからブランチを切って作業しましたが、追加で設定が必要でしょうか？
```
git push origin feature/nobuyuki-tsuchihashi
remote: Permission to SonicGarden/sg-romanizer.git denied to nobuoooo.
fatal: unable to access 'https://github.com/SonicGarden/sg-romanizer.git/': The requested URL returned error: 403
```

お手数おかけいたしますが、ご確認いただけますと幸いです。

**Comment by JunichiIto** [comment]
これ、たぶんフォークしたリポジトリではなく、弊社のリポジトリに直接pushしようとしてますね。
（弊社のリポジトリがoriginになっている）

いったん @nobuoooo さんがフォークしたリポジトリにコードをpushし、そこから弊社リポジトリに向けてPRを作成するようにしてください〜。

**Comment by nobuoooo** [comment]
@JunichiIto 
ご返信ありがとうございます！フォークの仕方に誤りがありましたが、無事にプッシュすることができました。
本日のイベントもよろしくお願いいたします！
